# fly.toml app configuration file generated for visabot-spring-surf-7310 on 2025-05-09T20:54:37+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "visabot-spring-surf-7310"
primary_region = "bom"

[build]

# Remove [http_service] block to prevent Fly from expecting a listening port
# Your bot doesn't need to accept HTTP requests

[env]
  PYTHONUNBUFFERED = "1"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1